import { randomUUID } from "node:crypto";

import { chat } from "@packages/llm-client";
import {
  agentFindingSchema,
  type AgentFinding,
  type Challenge,
  type Rebuttal
} from "@packages/shared-types";

import {
  createChallenge,
  createRebuttal,
  type ChallengeRequest,
  type EnrichedPipelineEvent,
  type RebuttalRequest
} from "./schemas.js";

type DetectionType =
  | "security_antipattern"
  | "null_dereference"
  | "generated_code_anomaly"
  | "general_code_regression";

type Detection = {
  type: DetectionType;
  evidence: string[];
  hypothesis: string;
  remediation: string;
  baseConfidence: number;
};

const AUTH_PAYMENT_PATH_PATTERN = /(auth|payment|billing|checkout|wallet|token|session|login|oauth)/i;
const securityPatterns = [
  /eval\s*\(/i,
  /new Function\s*\(/i,
  /innerHTML\s*=/i,
  /SELECT .* \+ .*FROM/i,
  /password\s*[:=]\s*['"]/i,
  /api[_-]?key\s*[:=]\s*['"]/i
];
const nullPatterns = [
  /\.\w+\.\w+/,
  /!\./,
  /\bas\s+\w+\b/,
  /non-null assertion/i
];
const generatedCodePatterns = [
  /TODO:.*verify/i,
  /placeholder implementation/i,
  /generated by ai/i,
  /lorem ipsum/i,
  /\/\/\s*fix later/i
];

const getDiffLines = (event: EnrichedPipelineEvent): string[] =>
  (event.context.gitDiff ?? "")
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.startsWith("+") || line.startsWith("-"));

const pickEvidence = (lines: string[], patterns: RegExp[]): string[] =>
  lines.filter((line) => patterns.some((pattern) => pattern.test(line))).slice(0, 5);

const detectCodeIssue = (event: EnrichedPipelineEvent): Detection => {
  const diffLines = getDiffLines(event);

  const securityEvidence = pickEvidence(diffLines, securityPatterns);
  if (securityEvidence.length > 0) {
    return {
      type: "security_antipattern",
      evidence: securityEvidence,
      hypothesis: "The diff introduces a security-sensitive anti-pattern that can weaken input handling or secret safety.",
      remediation: "Replace the unsafe construct with validated inputs and remove any embedded secrets from code.",
      baseConfidence: 0.6
    };
  }

  const nullEvidence = pickEvidence(diffLines, nullPatterns);
  if (nullEvidence.length > 0) {
    return {
      type: "null_dereference",
      evidence: nullEvidence,
      hypothesis: "The diff likely introduces an unsafe null or type assertion path that can fail at runtime.",
      remediation: "Add explicit null guards or safer typing before dereferencing the changed value.",
      baseConfidence: 0.55
    };
  }

  const generatedEvidence = pickEvidence(
    [...diffLines, ...(event.context.suspiciousPatterns ?? [])],
    generatedCodePatterns
  );
  if (generatedEvidence.length > 0) {
    return {
      type: "generated_code_anomaly",
      evidence: generatedEvidence,
      hypothesis: "The diff contains suspicious placeholder or generated-code artifacts that look insufficiently reviewed.",
      remediation: "Replace the placeholder logic with production-safe code and re-review the generated changes.",
      baseConfidence: 0.52
    };
  }

  return {
    type: "general_code_regression",
    evidence: diffLines.slice(0, 3),
    hypothesis: "The code diff may contain a regression, but the current evidence is not strongly diagnostic.",
    remediation: "Review the changed code paths manually and strengthen tests around the modified logic.",
    baseConfidence: 0.32
  };
};

export const scoreCodeConfidence = (event: EnrichedPipelineEvent, detection: Detection): number => {
  let score = detection.baseConfidence;

  if ((event.context.changedFiles ?? []).some((file) => AUTH_PAYMENT_PATH_PATTERN.test(file))) {
    score += 0.2;
  }

  if ((event.context.linkedCvssScore ?? 0) >= 7) {
    score += 0.3;
  }

  return Math.min(1, Number(score.toFixed(2)));
};

const maybeAskLlmForSummary = async (event: EnrichedPipelineEvent, detection: Detection): Promise<string | null> => {
  const evidence = detection.evidence.join("\n") || "No strong diff evidence provided.";

  try {
    const response = await chat(
      [
        {
          role: "system",
          content:
            "You summarize risky code diffs. Respond in one sentence with concrete code-review wording and no markdown."
        },
        {
          role: "user",
          content: [
            `Repository: ${event.repository}`,
            `Failure type: ${event.failureType}`,
            `Detected class: ${detection.type}`,
            "Evidence:",
            evidence
          ].join("\n")
        }
      ],
      {
        temperature: 0,
        maxTokens: 120,
        timeoutMs: 4_000
      }
    );

    return response.trim() || null;
  } catch {
    return null;
  }
};

export const analyzeCodeReview = async (event: EnrichedPipelineEvent): Promise<AgentFinding> => {
  const detection = detectCodeIssue(event);
  const confidence = scoreCodeConfidence(event, detection);
  const llmSummary = await maybeAskLlmForSummary(event, detection);

  return agentFindingSchema.parse({
    findingId: randomUUID(),
    agentId: "code_reviewer",
    eventId: event.eventId,
    hypothesis: llmSummary ?? detection.hypothesis,
    evidence:
      detection.evidence.length > 0
        ? detection.evidence
        : ["No high-signal risky code pattern was found in the supplied diff."],
    confidence,
    proposedRemediation: detection.remediation,
    createdAt: new Date()
  });
};

export const issueChallenges = async ({ findings }: ChallengeRequest): Promise<Challenge[]> => {
  const codeFinding = findings.find((finding) => finding.agentId === "code_reviewer");

  if (!codeFinding) {
    return [];
  }

  return findings
    .filter((finding) => finding.agentId !== "code_reviewer")
    .filter((finding) => codeFinding.confidence >= finding.confidence)
    .filter((finding) => codeFinding.evidence.length > 0)
    .map((finding) =>
      createChallenge({
        challengerAgentId: "code_reviewer",
        targetAgentId: finding.agentId,
        counterHypothesis: `The changed code paths more strongly support a code-level regression than ${finding.agentId}'s hypothesis.`,
        evidence: codeFinding.evidence.slice(0, 2),
        confidence: Math.min(1, Number((codeFinding.confidence - finding.confidence + 0.55).toFixed(2)))
      })
    );
};

export const createCodeRebuttal = async ({
  challenge,
  currentFinding
}: RebuttalRequest): Promise<Rebuttal> => {
  const mentionsCode = /code|auth|payment|null|security|diff/i.test(challenge.counterHypothesis);
  const position = mentionsCode && currentFinding ? "DEFEND" : "CONCEDE";
  const rebuttalFactor = position === "DEFEND" ? 0.85 : 0.7;
  const baseConfidence = currentFinding?.confidence ?? 0.4;
  const updatedConfidence =
    position === "DEFEND"
      ? Math.max(0, Number((baseConfidence * 0.97).toFixed(2)))
      : Math.max(0, Number((baseConfidence * 0.82).toFixed(2)));

  return createRebuttal({
    respondingAgentId: "code_reviewer",
    challengeId: challenge.challengeId,
    position,
    updatedConfidence,
    rebuttalFactor
  });
};
